--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5
-- Dumped by pg_dump version 17.5

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: approval; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.approval (
    approval_id bigint NOT NULL,
    approval_date date,
    approval_status character varying(255),
    remarks character varying(255),
    approver_id bigint,
    application_id bigint
);


ALTER TABLE public.approval OWNER TO postgres;

--
-- Name: approval_approval_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.approval ALTER COLUMN approval_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.approval_approval_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: approver; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.approver (
    approver_id bigint NOT NULL,
    digital_signature character varying(255),
    email character varying(255),
    name character varying(255),
    password character varying(255),
    role character varying(255)
);


ALTER TABLE public.approver OWNER TO postgres;

--
-- Name: approver_approver_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.approver ALTER COLUMN approver_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.approver_approver_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: booking; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.booking (
    booking_id bigint NOT NULL,
    booking_date date,
    event_date date,
    event_description character varying(255),
    event_name character varying(255),
    status character varying(255),
    time_slot character varying(255),
    venue_location character varying(255),
    venue_name character varying(255),
    end_time time(6) without time zone,
    start_time time(6) without time zone,
    event_id bigint,
    venue_id bigint
);


ALTER TABLE public.booking OWNER TO postgres;

--
-- Name: booking_booking_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.booking ALTER COLUMN booking_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.booking_booking_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: committee; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.committee (
    id bigint NOT NULL,
    committee_name character varying(255) NOT NULL,
    contact_email character varying(255),
    head_of_committee character varying(255),
    password character varying(255)
);


ALTER TABLE public.committee OWNER TO postgres;

--
-- Name: committee_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.committee ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.committee_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: event; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.event (
    event_id bigint NOT NULL,
    created_date date,
    event_date date NOT NULL,
    event_name character varying(255) NOT NULL,
    expected_participants integer,
    status character varying(255),
    committee_id bigint,
    venue_id bigint
);


ALTER TABLE public.event OWNER TO postgres;

--
-- Name: event_event_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.event ALTER COLUMN event_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.event_event_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: permission_application; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.permission_application (
    application_id bigint NOT NULL,
    permission_doc character varying(255),
    status character varying(255),
    upload_date date,
    event_id bigint
);


ALTER TABLE public.permission_application OWNER TO postgres;

--
-- Name: permission_application_application_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.permission_application ALTER COLUMN application_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.permission_application_application_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: venue; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.venue (
    venue_id bigint NOT NULL,
    available boolean,
    capacity integer,
    facilities character varying(255),
    venue_location character varying(255),
    venue_name character varying(255) NOT NULL
);


ALTER TABLE public.venue OWNER TO postgres;

--
-- Name: venue_venue_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.venue ALTER COLUMN venue_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.venue_venue_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: approval approval_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.approval
    ADD CONSTRAINT approval_pkey PRIMARY KEY (approval_id);


--
-- Name: approver approver_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.approver
    ADD CONSTRAINT approver_pkey PRIMARY KEY (approver_id);


--
-- Name: booking booking_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.booking
    ADD CONSTRAINT booking_pkey PRIMARY KEY (booking_id);


--
-- Name: committee committee_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.committee
    ADD CONSTRAINT committee_pkey PRIMARY KEY (id);


--
-- Name: event event_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.event
    ADD CONSTRAINT event_pkey PRIMARY KEY (event_id);


--
-- Name: permission_application permission_application_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.permission_application
    ADD CONSTRAINT permission_application_pkey PRIMARY KEY (application_id);


--
-- Name: venue venue_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.venue
    ADD CONSTRAINT venue_pkey PRIMARY KEY (venue_id);


--
-- Name: approval fk3ohlfs2lxyq5p3kifk619f7kd; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.approval
    ADD CONSTRAINT fk3ohlfs2lxyq5p3kifk619f7kd FOREIGN KEY (approver_id) REFERENCES public.approver(approver_id);


--
-- Name: booking fkiy2tdi4vrw2mljj6rqwmd698q; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.booking
    ADD CONSTRAINT fkiy2tdi4vrw2mljj6rqwmd698q FOREIGN KEY (event_id) REFERENCES public.event(event_id);


--
-- Name: event fkologv0b252fhcnqpe3dehhf; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.event
    ADD CONSTRAINT fkologv0b252fhcnqpe3dehhf FOREIGN KEY (committee_id) REFERENCES public.committee(id);


--
-- Name: booking fkp0qid0epicmuxn39fha72x6e8; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.booking
    ADD CONSTRAINT fkp0qid0epicmuxn39fha72x6e8 FOREIGN KEY (venue_id) REFERENCES public.venue(venue_id);


--
-- Name: permission_application fkqbgxrrsff7719arlyhb6fjqlm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.permission_application
    ADD CONSTRAINT fkqbgxrrsff7719arlyhb6fjqlm FOREIGN KEY (event_id) REFERENCES public.event(event_id);


--
-- Name: approval fkt96mhp96cxjlhtpygy7es29ak; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.approval
    ADD CONSTRAINT fkt96mhp96cxjlhtpygy7es29ak FOREIGN KEY (application_id) REFERENCES public.permission_application(application_id);


--
-- Name: event fkthgbmd6s6hp4l47kx1sh4cf9n; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.event
    ADD CONSTRAINT fkthgbmd6s6hp4l47kx1sh4cf9n FOREIGN KEY (venue_id) REFERENCES public.venue(venue_id);


--
-- PostgreSQL database dump complete
--

